version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login --region us-east-1 --no-include-email
      - REPOSITORY_URI=980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t web . 
      - docker tag web:latest 980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
